Update README.md
microsoftgraph/msgraph-cli pull request #254
Opened 2023-02-21 18:02 UTC by CarolKigoonya

2023-02-22 05:07 UTC, andrueastman submitted a review, later dismissed

2023-02-27 07:29 UTC, calebkiage requested changes

2023-02-27 07:29 UTC, calebkiage commented on README.md
> +## Creating the client application
What does this mean? Creating client application to me sounds like it's talking about creating an Azure AD client application. I think it should read: Logging in

2023-02-27 07:29 UTC, calebkiage commented on README.md
> +mgc login --strategy
```suggestion
mgc login --help
```

2023-02-27 13:52 UTC, calebkiage approved these changes

2023-02-27 13:53 UTC, merged