Dotnet tool
microsoftgraph/msgraph-cli pull request #312
Opened 2023-07-20 19:01 UTC by calebkiage

#174

2023-07-27 16:53 UTC, baywet requested changes

2023-07-27 16:53 UTC, baywet commented on src/msgraph-cli.csproj
> +    <PackageIconUrl>http://go.microsoft.com/fwlink/?LinkID=288890</PackageIconUrl>
```suggestion
    <PackageIconUrl>https://go.microsoft.com/fwlink/?LinkID=288890</PackageIconUrl>
```

2023-07-28 12:24 UTC, baywet approved these changes

2023-07-28 12:24 UTC, baywet commented on .azure-pipelines/release-cli.yaml
> +                    packagesToPush: "$(artifactsDownloadLocation)/nuget/Microsoft.Graph.Cli.*.nupkg"
should we also include the snupkg?

2023-07-28 12:33 UTC, calebkiage commented on .azure-pipelines/release-cli.yaml
> +                    packagesToPush: "$(artifactsDownloadLocation)/nuget/Microsoft.Graph.Cli.*.nupkg"
Ah, good point.

2023-07-28 12:36 UTC, baywet approved these changes

2023-07-28 12:49 UTC, merged