Add NuGet installation instructions
microsoftgraph/msgraph-cli pull request #315
Opened 2023-07-31 14:41 UTC by calebkiage

2023-07-31 15:07 UTC, baywet requested changes

2023-07-31 15:07 UTC, baywet commented on README.md
> +### Docker
```suggestion
### Dotnet tool
```

2023-08-02 15:42 UTC, baywet approved these changes

2023-08-03 06:45 UTC, andrueastman approved these changes

2023-08-07 10:49 UTC, merged